### ISSUE TITLE
Exploring Toastify: Implementing Real-Time Notifications in React

### ISSUE THREAD

**Issue by aa1588** [aa1588/campusXchange#13]
Related to User Story #1 
---
Description:
This task focuses on researching and understanding how to use **Toastify** to implement _real-time toast notifications_ in a React application. The goal is to explore how to provide user feedback through customizable and non-intrusive toast messages for various actions such as success, error, or info. The outcome will include a working example of triggering toast notifications in response to user interactions or API responses using Toastify.

**Comment by Raviteja-11-2002** [comment]
Install ` "react-toastify": "^10.0.5" `
`import { ToastContainer, toast } from 'react-toastify';`
```
<div className="App">
      <button className="custom-button" onClick={notify}>Show Success Toast</button>
      <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
      />
    </div>
```

```
const notify = () => {
    toast.success("Success! Your action was completed.", {
      position: "top-right",
      autoClose: 5000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      style: { backgroundColor: '#4caf50', color: '#fff' } // Custom background color for the toast
    });
```

**Comment by Raviteja-11-2002** [comment]
![Image](https://github.com/user-attachments/assets/fddda20e-41f6-496b-83dd-312c7f133abd)

Done!
