### ISSUE TITLE
Unit Test for Auth Service (Registration, Login, Account Activation, Forgot Password, Reset Password)

### ISSUE THREAD

**Issue by aa1588** [aa1588/campusXchange#30]
Related to User Story #1 
---

**Comment by aa1588** [comment]
@subhash-alapati Please learn unit testing in spring boot with Junit, AssertJ. Also let me know if you need help getting up to the speed with git.

**Comment by aa1588** [comment]
@subhash-alapati 

Reference: https://medium.com/@Lakshitha_Fernando/spring-boot-unit-testing-for-repositories-controllers-and-services-using-junit-5-and-mockito-def3ff5891be

**Comment by subhash-alapati** [comment]
Setup Your Spring Boot Project with JUnit and AssertJ
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.assertj</groupId>
    <artifactId>assertj-core</artifactId>
    <version>3.23.1</version> 
    <scope>test</scope>
</dependency>

Writing Unit Tests for Each Service
@Service
public class AuthService {

    public String register(UserRegistrationRequest request) {
        return "User Registered Successfully!";
    }

    public String login(LoginRequest request) {
        return "Login Successful!";
    }

    public String activateAccount(String token) {
        return "Account Activated!";
    }

    public String forgotPassword(String email) {
        return "Password Reset Email Sent!";
    }

    public String resetPassword(PasswordResetRequest request) {
        return "Password Reset Successful!";
    }
}

Writing Unit Tests for Each Functionality:
a. Unit Test for Registration
@SpringBootTest
class AuthServiceTest {

    @Autowired
    private AuthService authService;

    @Test
    void shouldRegisterUser() {
        UserRegistrationRequest request = new UserRegistrationRequest("user1", "user1@example.com", "password");
        String response = authService.register(request);
        assertThat(response).isEqualTo("User Registered Successfully!");
    }
}

b. Unit Test for Login
@Test
void shouldLoginUser() {
    LoginRequest loginRequest = new LoginRequest("user1", "password");
    String response = authService.login(loginRequest);
    assertThat(response).isEqualTo("Login Successful!");
}

c. Unit Test for Account Activation
@Test
void shouldActivateAccount() {
    String activationToken = "valid-token";
    String response = authService.activateAccount(activationToken);
    assertThat(response).isEqualTo("Account Activated!");
}

d. Unit Test for Forgot Password
@Test
void shouldSendPasswordResetEmail() {
    String email = "user1@example.com";
    String response = authService.forgotPassword(email);
    assertThat(response).isEqualTo("Password Reset Email Sent!");
}

e. Unit Test for Reset Password
@Test
void shouldResetPassword() {
    PasswordResetRequest passwordResetRequest = new PasswordResetRequest("user1@example.com", "new-password");
    String response = authService.resetPassword(passwordResetRequest);
    assertThat(response).isEqualTo("Password Reset Successful!");
}


Mocking Dependencies
@MockBean
private UserRepository userRepository;

@Test
void shouldRegisterUserWithMockedRepo() {
    UserRegistrationRequest request = new UserRegistrationRequest("user1", "user1@example.com", "password");
    when(userRepository.save(any(User.class))).thenReturn(new User());
    String response = authService.register(request);
    assertThat(response).isEqualTo("User Registered Successfully!");
}


AssertJ for Advanced Assertions
assertThat(response)
    .isNotNull()
    .startsWith("User")
    .contains("Registered")
    .endsWith("Successfully!");
![Image](https://github.com/user-attachments/assets/7078e0b6-da20-4445-b434-a5989e1fe1ea)
![Image](https://github.com/user-attachments/assets/5a2afbdc-a263-447a-b42a-cf55fb180b03)
![Image](https://github.com/user-attachments/assets/26fcbca7-a489-4b78-ab7f-39ef5364c122)
![Image](https://github.com/user-attachments/assets/a234ad5e-be7c-4ce7-af88-211f31dcc19f)

**Comment by aa1588** [comment]
@subhash-alapati This needs to be part of the main codebase. Lets meet after the class Monday, I will explain in details about the task.

**Comment by subhash-alapati** [comment]
okayyy sure amrit!!!!

**Comment by subhash-alapati** [comment]
```
package com.unt.campusxchange.users.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.AssertionsForClassTypes.assertThatThrownBy;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.unt.campusxchange.users.entity.AccountStatus;
import com.unt.campusxchange.users.entity.User;
import com.unt.campusxchange.users.exception.InvalidOTPException;
import com.unt.campusxchange.users.exception.UserNotFoundException;
import com.unt.campusxchange.users.repo.UserRepository;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class AuthServiceTest {

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private AuthService userService;

    private User user;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        user = new User();
        user.setId(1);
        user.setOtp("123456");
        user.setAccountStatus(AccountStatus.INACTIVE); // Assume inactive by default
    }

    @Test
    public void shouldActivateAccountWithValidOTP() {
        // Arrange
        when(userRepository.findById(1)).thenReturn(Optional.of(user));

        // Act
        boolean result = userService.activateAccount(1, "123456");

        // Assert
        assertThat(result).isTrue();
        assertThat(user.getAccountStatus()).isEqualTo(AccountStatus.ACTIVE);
        verify(userRepository).save(user); // Verify that the save method is called
    }

    @Test
    public void shouldThrowExceptionForInvalidOTP() {
        // Arrange
        when(userRepository.findById(1)).thenReturn(Optional.of(user));

        // Act & Assert
        assertThatThrownBy(() -> userService.activateAccount(1, "654321"))
                .isInstanceOf(InvalidOTPException.class)
                .hasMessageContaining("Provided OTP 654321 doesn't match our records");

        verify(userRepository, never()).save(user); // Verify that save is never called
    }

    @Test
    void testGenerateOTP() {
        // Call the method
        String otp = AuthService.generateOTP();

        // Assert that the OTP is a 4-digit number
        assertThat(otp).isNotNull();
        assertThat(otp.length()).isEqualTo(4);

        // Assert that the OTP is between 1000 and 9999
        int otpInt = Integer.parseInt(otp);
        assertThat(otpInt).isBetween(1000, 9999);
    }

    @Test
    public void shouldThrowExceptionWhenUserNotFound() {
        // Arrange
        when(userRepository.findById(2)).thenReturn(Optional.empty());

        // Act & Assert
        assertThatThrownBy(() -> userService.activateAccount(2, "123456"))
                .isInstanceOf(UserNotFoundException.class)
                .hasMessageContaining("User not found with given id: 2");

        verify(userRepository, never()).save(user); // Verify that save is never called
    }

    @Test
    void activateAccount() {}

    @Test
    void login() {}
}

```

**Comment by subhash-alapati** [comment]
![Image](https://github.com/user-attachments/assets/51afa057-119e-47a5-a63c-f7d4c250c0d9)
