### ISSUE TITLE
Frontend items module Unit Testing

### ISSUE THREAD

**Issue by aa1588** [aa1588/campusXchange#90]
Realated to User Story #3 
---

**Comment by subhash-alapati** [comment]
![Image](https://github.com/user-attachments/assets/8255b0eb-4965-4557-82c1-613cce9396ce)


@aa1588  unable to resolve this issue regarding unit testing with jest.

**Comment by aa1588** [comment]
@sudinjoshi

**Comment by aa1588** [comment]
Bug - Changed priority to **LOW**
